name: Release InvisibleKiller

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Maven
        run: mvn clean package

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar
          generate_release_notes: true

      - name: Publish to Modrinth & CurseForge
        uses: Kir-Antipov/mc-publish@v3
        with:
          files: target/*.jar
          name: InvisibleKiller ${{ github.ref_name }}
          version: ${{ github.ref_name }}

          modrinth-id: SZFrOxDw
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          curseforge-id: 1443029
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}


          loaders: |
            paper
            purpur

          game-versions: |
            1.21
            1.21.1
            1.21.2
            1.21.3
            1.21.4
            1.21.5
            1.21.6
            1.21.7
            1.21.8
            1.21.9
            1.21.10
            1.21.11

          changelog: |
            See GitHub release:
            https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}
